config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :forms
  resources :questions
  resources :choices

  get    'sessions/new'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/FormQuestions/:id', to: 'forms#showFormQuestions'
  post   '/FormQuestions/:id', to: 'forms#submitFormQuestions'
  get    '/results/:id/', to: 'forms#results'
  post   '/results/:id/', to: 'forms#results'
  get    '/forms/new', to: 'forms#new'
  post   '/forms/new', to: 'forms#create'
  get    '/questions/new/:id', to: 'questions#new_ques'
  post   '/questions/new/:id', to: 'questions#create'

  root "forms#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :form
  has_many :choices
  has_many :form_answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/new/:id
  def new_ques
    @question = Question.new
    @form = Form.find(params[:id])
    @question.form = @form
    render '_form_new'
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.choices = Array.new()

    respond_to do |format|
      if @question.question_type!="text"
        params[:form][:question].each_with_index do |ques|
          ques[:choice].each_with_index do |choice|
            if choice!=''
              my_choice = Choice.new
              my_choice.name = choice
              @question.choices.push(my_choice)
            end
          end
        end
      end
      if @question.choices.length
        if @question.save
          @question.choices.each do |choice|
            choice.question_id = @question.id
            choice.save
          end
          format.html { redirect_to @question.form, notice: 'Question was successfully created.' }
          format.json { render :show, status: :created, location: @question }
        else
          format.html { render :new }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question.form, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    my_form = @question.form
    if @question.question_type != 'text'
      @question.choices.each do |choice|
        choice.destroy
      end
    end
    @question.destroy
    respond_to do |format|
      format.html { redirect_to my_form, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.fetch(:question).permit(:name, :question_type, :form_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-sm-12
      .form-group
        %label.inputdefault
          = f.label :name
        = f.text_field :name, :class=>"form-control", :placeholder=>:name

  .col-sm-12.text-center
    .actions
      %br
      = f.submit 'Save', :class=>"btn btn-primary"

app/views/questions/_form_new.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg
  =f.hidden_field :form_id, value: @question.form.id

  .row
    .col-sm-10
      .form-group
        %label.inputdefault
          = f.label :name
        = f.text_field :name, :class=>"form_questions_type form-control", :placeholder=>:name
    .col-sm-2
      .form-group
        %label.inputdefault
          = f.label :question_type
        = f.select :question_type, options_for_select([['Text','text'], ['DropDown','dropdown'], ['CheckBoxes (Multi Select)','checkboxes'],['Radio Buttons (Only One Select)','radiobuttons']]),{}, {:class=>"form-control form_questions_type",:data=>{:id=>"#{@question.id}"}}

  .row
    .col-sm-12{:id => "choices_container_#{@question.id}", :class=>"choices_container_#{@question.id}"}

  .col-sm-12.text-center
    .actions
      %br
      = f.submit 'Save', :class=>"btn btn-primary"

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Back', @question.form

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @questions.each do |question|
      %tr
        %td= link_to 'Show', question
        %td= link_to 'Edit', edit_question_path(question)
        %td= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question', new_question_path

app/views/questions/new.html.haml
%h1 New question

= render 'form'

app/views/questions/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path