config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :forms
  resources :questions
  resources :choices

  get    'sessions/new'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/FormQuestions/:id', to: 'forms#showFormQuestions'
  post   '/FormQuestions/:id', to: 'forms#submitFormQuestions'
  get    '/results/:id/', to: 'forms#results'
  post   '/results/:id/', to: 'forms#results'
  get    '/forms/new', to: 'forms#new'
  post   '/forms/new', to: 'forms#create'
  get    '/questions/new/:id', to: 'questions#new_ques'
  post   '/questions/new/:id', to: 'questions#create'

  root "forms#index"

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
  has_many :form_answers
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(choice_params)

    respond_to do |format|
      if @choice.save
        format.html { redirect_to @choice, notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to @choice.question.form, notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    my_form = @choice.question.form
    my_question = @choice.question
    if my_question.choices.length>1
      @choice.destroy
      message = 'Choice was successfully destroyed.'
    else
      message = 'Choice note deleted: You cannot delete all choices'
    end
    respond_to do |format|
      format.html { redirect_to my_form, notice: message}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.fetch(:choice).permit(:name)
    end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_form.html.haml
= form_for @choice do |f|
  - if @choice.errors.any?
    #error_explanation
      %h2= "#{pluralize(@choice.errors.count, "error")} prohibited this choice from being saved:"
      %ul
        - @choice.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-sm-12
      .form-group
        %label.inputdefault
          = f.label :name
        = f.text_field :name, :class=>"form-control", :placeholder=>:name

  .col-sm-12.text-center
    .actions
      %br
      = f.submit 'Save', :class=>"btn btn-primary"

app/views/choices/edit.html.haml
%h1 Editing choice

= render 'form'

= link_to 'Show', @choice
\|
= link_to 'Back', choices_path

app/views/choices/index.html.haml
%h1 Listing choices

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @choices.each do |choice|
      %tr
        %td= link_to 'Show', choice
        %td= link_to 'Edit', edit_choice_path(choice)
        %td= link_to 'Destroy', choice, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Choice', new_choice_path

app/views/choices/new.html.haml
%h1 New choice

= render 'form'

= link_to 'Back', choices_path

app/views/choices/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_choice_path(@choice)
\|
= link_to 'Back', choices_path