config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :forms
  resources :questions
  resources :choices

  get    'sessions/new'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/FormQuestions/:id', to: 'forms#showFormQuestions'
  post   '/FormQuestions/:id', to: 'forms#submitFormQuestions'
  get    '/results/:id/', to: 'forms#results'
  post   '/results/:id/', to: 'forms#results'
  get    '/forms/new', to: 'forms#new'
  post   '/forms/new', to: 'forms#create'
  get    '/questions/new/:id', to: 'questions#new_ques'
  post   '/questions/new/:id', to: 'questions#create'

  root "forms#index"

end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ActiveRecord::Base

  validates :username, uniqueness: true
  validates :email, presence: true, email: true
  has_secure_password
  # def authenticate(pass)
  #   if pass=self.pass
  #     return true
  #   else
  #     return false
  #   end
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, :only=>[:new,:create]
  before_filter :require_logout, :only=>[:new,:create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :first_name, :last_name, :email, :gender)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    .alert.alert-danger#error_explanation
      %strong= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-sm-6
      .form-group
        %label.inputdefault
          = f.label :username
        = f.text_field :username, :class=>"form-control", :placeholder=>:username

    .col-sm-6
      .form-group
        %label.inputdefault
          = f.label :password
        = f.password_field :password, :class=>"form-control", :placeholder=>:password

    .col-sm-6
      .form-group
        %label.inputdefault
          = f.label :email
        = f.email_field :email, :class=>"form-control", :placeholder=>:email

    .col-sm-6
      .form-group
        %label.inputdefault
          = f.label :gender
        = f.select :gender , [['Male','0'],['Female','1']], {}, {:class=>"form-control"}

    .col-sm-6
      .form-group
        %label.inputdefault
          = f.label :first_name
        = f.text_field :first_name, :class=>"form-control", :placeholder=>:first_name

    .col-sm-6
      .form-group
        %label.inputdefault
          = f.label :last_name
        = f.text_field :last_name, :class=>"form-control", :placeholder=>:last_name

    .col-sm-12.text-center
      .actions
        = f.submit 'Save', :class=>"btn btn-primary"

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

app/views/users/index.html.haml
.box-header.with-border
  %h1.box-title Listing users
.box-body
  %table.table
    %thead
      %tr
        %th User Name
        %th Email
        %th First Name
        %th Last Name
        %th{:colspan=>3}

    %tbody
      - @users.each do |user|
        %tr
          %td= user.username
          %td= user.email
          %td= user.first_name
          %td= user.last_name
          %td= link_to 'Show', user
          %td= link_to 'Edit', edit_user_path(user)
          %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
.box-header.with-border
  %h1.box-title Register New User
.box-body
  = render 'form'

= link_to 'Back to login', '/login'

app/views/users/show.html.haml
.box-header.with-border
  %h1.box-title Update #{@user.username}

.box-body
  = render 'form'