config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :forms
  resources :questions
  resources :choices

  get    'sessions/new'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/FormQuestions/:id', to: 'forms#showFormQuestions'
  post   '/FormQuestions/:id', to: 'forms#submitFormQuestions'
  get    '/results/:id/', to: 'forms#results'
  post   '/results/:id/', to: 'forms#results'
  get    '/forms/new', to: 'forms#new'
  post   '/forms/new', to: 'forms#create'
  get    '/questions/new/:id', to: 'questions#new_ques'
  post   '/questions/new/:id', to: 'questions#create'

  root "forms#index"

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy, :results, :showFormQuestions, :submitFormQuestions]
  skip_before_filter :require_login, :only=>[:showFormQuestions,:submitFormQuestions]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.where({:user_id => current_user().id})
    if @forms
      render :index
    else
      render :error
    end
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
    if @form != false
      render :show
    else
      render :error
    end
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
    if @form != false
      render :edit
    else
      render :error
    end
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)
    @form.user_id = current_user().id

    respond_to do |format|
      valid = true
      questions = Array.new
      if params[:form].has_key?(:question)
        params[:form][:question].each_with_index do |question|
          my_question = Question.new
          if question[:name]==''
            @form.errors.add(:base,'Some Questions Are Empty')
            valid = false
            break
          else
            my_question.name = question[:name]
            my_question.question_type = question[:question_type]
          end
          if question[:question_type]!='text'
            if question.has_key?(:choice)
              question[:choice].each_with_index do |choice|
                if choice!=''
                  my_choice = Choice.new
                  my_choice.name = choice
                  my_question.choices.push(my_choice)
                else
                  @form.errors.add(:base,'Some Choices Are Empty')
                  valid = false
                  break
                end
              end
            else
              @form.errors.add(:base,'None Text Questions Not Have Choices')
              valid = false
              break
            end
          end
          questions.push(my_question)
        end
      else
        @form.errors.add(:base,'Undefined Questions')
        valid = false
      end
      if valid && @form.save
        questions.each do |question|
          question.form_id = @form.id
          if question.save
            question.choices.each do |choice|
              choice.question_id = question.id
              choice.save
            end
          end
        end
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    if @form != false
      respond_to do |format|
        if @form.update(form_params)
          format.html { redirect_to @form, notice: 'Form was successfully updated.' }
          format.json { render :show, status: :ok, location: @form }
        else
          format.html { render :edit }
          format.json { render json: @form.errors, status: :unprocessable_entity }
        end
      end
    else
      render :error
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    if @form != false
      @form.questions.each do |question|
        if question.question_type != 'text'
          question.choices.each do |choice|
            choice.destroy
          end
        end
        question.destroy
      end
      @form.destroy
      respond_to do |format|
        format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      render :error
    end
  end

  # ShowForm /forms/1/
  def showFormQuestions
    if current_user().id == @form.user_id
      @form_answer = FormAnswer.new
      @form_answer.form = @form
      render :show_form
    else
      respond_to do |format|
        format.html { redirect_to forms_url, notice: 'You cannot answer your form.' }
        format.json { head :no_content }
      end
    end
  end

  # submit_answer
  def submitFormQuestions
    if current_user().id == @form.user_id
      @form.questions.each do |question|
        @answers = params["ques_#{question.id}"]
        if !@answers.kind_of?(Array)
          @answers = [@answers]
        end
        @answers.each do |answer|
          form_answer = FormAnswer.new
          form_answer.form_id = @form.id
          form_answer.question_id = question.id
          form_answer.answer = answer
          if question.question_type != 'text'
            choice = Choice.find(answer)
            form_answer.choice_id = choice.id
            form_answer.answer = choice.name
          end
          form_answer.save
        end
      end
      respond_to do |format|
        format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to forms_url, notice: 'You cannot answer your form.' }
        format.json { head :no_content }
      end
    end
  end

  # GET results/1
  # POST results/1
  # POST results/1.pdf
  def results
    @format = 'html'
    where_statement = {}
    where_statement[:form_id] = @form.id
    joins = {:question=>{}}
    if params[:question] && params[:question]!=''
      where_statement[:question_id] = params[:question]
    end
    if params[:question_type] && params[:question_type]!=''
      where_statement[:questions] = {:question_type=>params[:question_type]}
    end
    @answers = FormAnswer.joins(:question).where(where_statement)
    respond_to do |format|
      format.html
      format.pdf do
        @format = 'pdf'
        render :pdf => 'report', :layout=>'pdf.html.haml'
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.where({:id=>params[:id],:user_id=>current_user().id})
      if @form.length>0
        @form = @form[0]
      else
        @form = false
      end
    end
    def set_public_form
      @form = Form.where({:id=>params[:id],:user_id=>current_user().id})
      if @form.length>0
        @form = @form[0]
      else
        @form = false
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.fetch(:form).permit(:name, :desc)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.haml
= form_for @form do |f|
  - if @form.errors.any?
    .alert.alert-danger#error_explanation
      %strong= "#{pluralize(@form.errors.count, "error")} prohibited this form from being saved:"
      %ul
        - @form.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-sm-12
      .form-group
        %label.inputdefault
          = f.label :name
        = f.text_field :name, :class=>"form-control", :placeholder=>:name
  .row
    .col-sm-12
      .form-group
        %label.inputdefault
          = f.label :desc
        = f.text_area :desc, :class=>"form-control", :placeholder=>:desc

  -if params[:action] == 'new' or params[:action] == 'create'
    .row
      .col-sm-12.text-center
        %label#add_form_question.btn.btn-alert
          Add Question
    %br
    .row
      .col-sm-12#form-questions

  .col-sm-12.text-center
    .actions
      %br
      = f.submit 'Save', :class=>"btn btn-primary"

app/views/forms/edit.html.haml
%h1 Editing form

= render 'form'

= link_to 'Show', @form
\|
= link_to 'Back', forms_path

app/views/forms/error.haml
.alert.alert-danger
  .text-center
    %h1
      Check Url

app/views/forms/index.html.haml
%h1 Listing forms

%table.table
  %thead
    %tr
      %th
        Form Name
      %th{:colspan=>3}

  %tbody
    - @forms.each do |form|
      %tr
        %td= form.name
        %td= link_to 'Show', form
        %td= link_to 'Results', "/results/#{form.id}"
        %td= link_to 'Edit', edit_form_path(form)
        %td= link_to 'Destroy', form, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Form', new_form_path

app/views/forms/new.html.haml
%h1 New form

= render 'form'

= link_to 'Back', forms_path

app/views/forms/results.haml
.alert.alert-success
  .row
    .col-sm-12
      %center
        %h2
          =@form.name
  .row
    .col-sm-12
      %p
        =@form.desc

%form{ :method => 'get' }
  %table.table.table-striped{ @format=='pdf' ? {:width=>'100%',:border=>1 }:{}}
    %thead
      %tr
        %th
          Question
        %th
          Question Type
        %th
          Answer
        %th
          Choice
        - if @format == 'html'
          %th
      - if @format == 'html'
        %tr
          %th
            %select{:name=>'question'}
              %option{:value=>''}
                All Questions
              -@form.questions.each do |question|
                %option{:value=> "#{question.id}", :selected=>params[:question]=="#{question.id}"}
                  =question.name
          %th
            %select{:name=>'question_type'}
              %option{:value=>''}
                All Types
              %option{:value=>'text', :selected=>params[:question_type]=='text'}
                Text
              %option{:value=>'dropdown', :selected=>params[:question_type]=='dropdown'}
                DropDown
              %option{:value=>'checkboxes', :selected=>params[:question_type]=='checkboxes'}
                CheckBoxes (Multi Select)
              %option{:value=>'radiobuttons', :selected=>params[:question_type]=='radiobuttons'}
                Radio Buttons (Only One Select)
          %th
          %th
          %th
            %input{:type=>'submit',:value=>'Search'}
            =link_to 'Print',params.merge(:format=>:pdf), {:target=>'blank'}
    %tbody
      -@answers.each do |form_answer|
        %tr
          %td
            =form_answer.question.name
          %td{ @format=='pdf' ? {:align=>'center'}:{}}
            =form_answer.question.question_type
          %td{ @format=='pdf' ? {:align=>'center'}:{}}
            =form_answer.answer
          %td{ @format=='pdf' ? {:align=>'center'}:{}}
            -if form_answer.choice
              =form_answer.choice.name
            -else
              = '-'
          - if @format == 'html'
            %td

- if @format == 'html'
  = link_to 'Back', forms_path

app/views/forms/show.html.haml
%p#notice= notice
.row
  .col-sm-12
    %h3
      =@form.name
  .col-sm-12
    %p
      =@form.desc
  .row
    .col-sm-12
      %table.table
        %tr
          %th{:width=>"60%"} Name
          %th{:width=>"20%"} Type
          %th{:width=>"20%"}
        -@form.questions.each do |question|
          %tr
            %td
              -if question.question_type!='text'
                .panel.panel-default
                  .panel-heading
                    %h4.panel-title
                      %a{:href=>"#collapse#{question.id}",:data=>{"toggle"=>"collapse"}}
                        =question.name
                  .panel-collapse.collapse{:id=>"collapse#{question.id}"}
                    %table.table.panel-body
                      %tr
                        %th
                          Choices
                        %th
                      -question.choices.each do |choice|
                        %tr
                          %td
                            =choice.name
                          %td
                            =link_to 'Edit', edit_choice_path(choice)
                            \|
                            = link_to 'Destroy', choice, :method => :delete, :data => { :confirm => 'Are you sure?' }
              -else
                =question.name
            %td
              =question.question_type
            %td
              =link_to 'Edit', edit_question_path(question)
              \|
              = link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to 'Results', "/results/#{@form.id}"
\|
= link_to 'Edit', edit_form_path(@form)
\|
= link_to 'Back', forms_path
\|
=link_to 'Add New Question', "/questions/new/#{@form.id}"
%br
%br
%br
.alert.alert-danger
  .text-center
    %strong
      Copy link below and share this form to answer it
    %br
    ="#{request.protocol + request.host}:#{request.port.to_s}/FormQuestions/#{@form.id}"

app/views/forms/show_form.haml
%Form{:for=>@form, :action=>"/FormQuestions/#{@form.id}", :method=>"post"}
  %hidden_field{name:"id",value:@form.id}
  %h3
    =@form.name
  %p
    =@form.desc
  %ul
    -@form.questions.each do |question|
      %li
        %label
          =question.name
        .row
          -case question.question_type

            -when 'text'
              .col-sm-12
                .form-group
                  %textarea.form-control#answer{name:"ques_#{question.id}",placeholder:question.name,col:2}

            -when 'checkboxes'
              -question.choices.each do |choice|
                .col-sm-3
                  .checkbox-inline
                    %label
                      %input#checkbox{name:"ques_#{question.id}[]",value:choice.id,type:'checkbox'}
                      =choice.name

            -when 'radiobuttons'
              -question.choices.each do |choice|
                .col-sm-3
                  .radio-inline
                    %label
                      %input{name:"ques_#{question.id}",value:choice.id,type:'radio'}
                      =choice.name

            -when 'dropdown'
              .col-sm-12
                .form-group
                  %select.form-control{name:"ques_#{question.id}"}
                    -question.choices.each do |choice|
                      %option{value:choice.id}
                        =choice.name

            -else
              .col-sm-12

  .col-sm-12.text-center
    .actions
      %br
      %input.btn.btn-primary{type:"submit"}

app/views/forms/submit_answer.haml
.row
  .col-sm-12
    .alert.alert-success
      %h2
        Thank You For Answering Form Question